#!/usr/bin/env python3
"""Generate a minimal pytest-style reproduction stub next to a target file.

Given the file and line where a bug was reported, this script:
  1. finds the enclosing function/method definition,
  2. writes a `test_repro.py` next to the target file,
  3. includes a call skeleton to that function and one failing assert.

Pure Python standard library. Deterministic for a given input.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import List, Optional

DEF_RE = re.compile(r"^(\s*)(?:async\s+def|def|class)\s+(\w+)\s*\(?")
SIG_RE = re.compile(r"^\s*(?:async\s+def|def)\s+(\w+)\s*\((.*?)\)\s*:")


def find_enclosing(lines: List[str], target_line: int):
    """Return the innermost def/class whose block contains target_line."""
    defs = []
    for i, line in enumerate(lines, start=1):
        m = DEF_RE.match(line)
        if m:
            defs.append({"line": i, "indent": len(m.group(1)), "name": m.group(2)})
    if not defs:
        return None
    for idx, d in enumerate(defs):
        end = len(lines) + 1
        for nxt in defs[idx + 1 :]:
            if nxt["indent"] <= d["indent"]:
                end = nxt["line"]
                break
        d["end"] = end
    candidates = [d for d in defs if d["line"] <= target_line < d["end"]]
    if not candidates:
        return None
    candidates.sort(key=lambda d: (d["indent"], d["line"]))
    return candidates[-1]


def skeleton_args(lines: List[str], func_line: int) -> str:
    """Build a comma-separated argument skeleton from a def signature."""
    if func_line < 1 or func_line > len(lines):
        return ""
    sig = SIG_RE.match(lines[func_line - 1])
    if not sig:
        return ""
    inside = sig.group(2).strip()
    if not inside:
        return ""
    parts = [p.strip() for p in inside.split(",") if p.strip()]
    names = []
    for p in parts:
        if p.startswith("*"):
            continue
        name = p.split("=")[0].split(":")[0].strip()
        if name in ("self", "cls"):
            continue
        if name:
            names.append(name)
    return ", ".join(names)


def module_name(stem: str) -> str:
    """Turn a filename stem into a safe Python module identifier."""
    mod = re.sub(r"[^0-9A-Za-z_]", "_", stem)
    if mod and not re.match(r"^[A-Za-z_]", mod):
        mod = "_" + mod
    return mod or "_module"


def build_test(module: str, func: str, relpath: Path, line: int,
               test_cmd: Optional[str], args_str: str) -> str:
    call = f"{module}.{func}({args_str})" if func else f"{module}"
    run_hint = test_cmd or f"pytest {relpath.parent / 'test_repro.py'} -q"
    return f'''# Auto-generated by agentic-debugger make_repro.
# Reproduces the failure reported at: {relpath}:{line}
# Suggested run command: {run_hint}
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import {module}  # noqa: E402


def test_repro_line_{line}():
    """Minimal reproduction for the reported failure.

    Drive {call} with the inputs that reach {relpath}:{line}, then assert
    the correct behavior. The placeholder assert fails on purpose so this
    test is red before the fix and must turn green after the fix.
    """
    result = {call}

    # TODO: replace with a real expectation once inputs are known.
    assert False, (
        f"repro not driven yet: result={{result!r}}; call {call} with inputs "
        f"that fail at {relpath}:{line}"
    )
'''


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate a pytest-style reproduction stub next to a file."
    )
    parser.add_argument("--file", required=True, help="Target source file path.")
    parser.add_argument(
        "--line", required=True, type=int, help="Reported line number (1-based)."
    )
    parser.add_argument(
        "--test-cmd", default=None, help="Suggested test command to embed."
    )
    args = parser.parse_args(argv)

    target = Path(args.file)
    if not target.is_file():
        sys.exit(f"[make_repro] file not found: {args.file}")
    if args.line < 1:
        sys.exit(f"[make_repro] --line must be >= 1, got {args.line}")

    try:
        text = target.read_text(encoding="utf-8")
    except OSError as exc:
        sys.exit(f"[make_repro] cannot read {args.file!r}: {exc}")

    lines = text.splitlines()
    if args.line > len(lines):
        sys.exit(
            f"[make_repro] --line {args.line} exceeds file length {len(lines)}"
        )

    enclosing = find_enclosing(lines, args.line)
    module = module_name(target.stem)
    func = enclosing["name"] if enclosing else ""
    args_str = skeleton_args(lines, enclosing["line"]) if enclosing else ""

    out_path = target.parent / "test_repro.py"
    content = build_test(module, func, target, args.line, args.test_cmd, args_str)
    if out_path.exists():
        sys.stderr.write(f"[make_repro] warning: overwriting existing {out_path}\n")
    out_path.write_text(content, encoding="utf-8")

    print(f"[make_repro] wrote {out_path}")
    print(
        f"[make_repro] target={target}:{args.line} "
        f"module={module} func={func or '(module-level)'}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
